apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP
  namespace: $NAMESPACE
  labels:
    app: $APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: $APP
    spec:
      nodeSelector:
        storage: "false"
      containers:
        - name: $APP
          image: $IMAGE
      imagePullSecrets:
        - name: k8net-registry-secret
